= RHAMT Helper

rhamt-helper automates the following tasks:

* build of the Red Hat Application Migration Toolkit (RHAMT) CLI
* batch analysis of several Java applications grouped subfolders


== Usage

1. Copy the applications you want to analyze in sub-directories of "02__apps"
+
For performance reasons, it is not recommended to analyze more than 1 GB of applications in a same report. Split the applications you want to analyze in several sub-directories of "02__apps".

2. (optional) Adjust the configuration
+
** 01_build_RHAMT.sh
+
*** *RHAMT_BASE_REPO*: RHAMT CLI code base. Can be updated to point to the official repository "windup" instead of the stable/patched one "Maarc".
+
** 02_analyze_apps.sh
+
*** *MAX_MEMORY*: max Java Heap used by the RHAMT CLI
*** *MAX_METASPACE_SIZE*: max Java Metasapce used by the RHAMT CLI
*** *PACKAGES*: Java packages decompiled during the analysis ("" -> decompiles everything, "de nl" -> decompiles de.* and nl.* packages)
*** *TARGET* RHAMT targets

3. Execute "./run.sh"

4. View the results in "02__reports"


== Important

While analyzing an important amount of applications, it is key to:

* increase the default ulimit on your operating system
+
This is done by "00_update_ulimit.sh" (for MacOS users) or by following the instructions on https://access.redhat.com/solutions/60746[this article] for RHEL/Fedora users.

* select the proper Java packages to be decompiled (PACKAGES)

* set a proper value for the JVM space (MAX_MEMORY, MAX_METASPACE_SIZE)
